// Like vtkColorMaps.rgbPresetNames, but more selective
const ColorPresetNames = [
  'Grayscale',
  'X Ray',
  'Viridis (matplotlib)',
  'Plasma (matplotlib)',
  'Inferno (matplotlib)',
  'Magma (matplotlib)',
  'gray_Matlab',
  'bone_Matlab',
  'pink_Matlab',
  '2hot',
  'gist_earth',
  'copper_Matlab',
  'Haze',
  'Haze_green',
  'Haze_lime',
  'Haze_cyan',
  'Asymmtrical Earth Tones (6_21b)',
  'Green-Blue Asymmetric Divergent (62Blbc)',
  'Muted Blue-Green',
  'Black, Blue and White',
  'Black, Orange and White',
  'Black-Body Radiation',
  'Cool to Warm',
  'Cool to Warm (Extended)',
  'Warm to Cool',
  'Warm to Cool (Extended)',
  'Blue to Red Rainbow',
  'Red to Blue Rainbow',
  'jet',
  'rainbow',
  'hsv',
  'Rainbow Desaturated',
  'Cold and Hot',
  'Rainbow Blended Black',
  'Rainbow Blended Grey',
  'Rainbow Blended White',
  'nic_CubicL',
  'Spectral_lowBlue',
  'Yellow 15',
  'magenta',
  'blue2cyan',
  'Blues',
  'Greens',
  'Reds',
  'Purples',
  'Oranges',
  'PuBu',
  'BuPu',
  'BuGn',
  'GnBu',
  'GnBuPu',
  'BuGnYl',
  'PuRd',
  'RdPu',
  'RdOr',
  'BrOrYl',
  'RdOrYl',
  'BuRd',
  'GnRP',
  'GYPi',
  'GnYlRd',
  'GBBr',
  'PuOr',
  'PRGn',
  'PiYG',
  'OrPu',
  'BrBG',
  'GyRd',
];

export default ColorPresetNames;
